sudo: false
language: ruby
rvm:
  - 2.5.3
services:
  - redis-server
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_latest.gemfile
before_install: gem install bundler -v 1.17.3
script:
  - bundle exec rspec --exclude-pattern "spec/integration/**/*_spec.rb"
  - bundle exec rspec spec/integration/rails_spec.rb
  - bundle exec rspec spec/integration/rails_custom_timezones_spec.rb
deploy:
  provider: rubygems
  api_key:
    secure: UK/XPRcsRv84se63pUdb2MEv6No02N7bZl1gkXwB4Lsyc/ny9GTrtf0uBLIAcnZxJ26CSuN0IBrN8lHC+UM8Js+uKAsSOgTW/15Oik5p6cv/rUCOeyLVWvA99JRuq8NlvblDRVsWDRTs/i9TmTlJdy6ZO2K1yqrxIs7btTCPxD7sglrZMNHKRoFXe/dQ73BrM7YK1gOjIo7V75MAqSoG1E1TC9jRgdz4V9JftQph1I+S8PyhKz/XGiUXaJHHJm4K0HmgtClU0xZlw2CrUEMoxRLajjhIEgkwuNRlJsjKE2qBvgMnKZcwpZwgaDi8cDim4/ieC4Th/KkvQweQVfaZhnK9LIeG9vy71VOafjxD4DJn6JMl3Cc4pVtwmyvWz2P89IF8Wl3tVMp5vE4nHt26P7o534ke1n8fhiHJk043lFQ9A+XuZ+LKKEywnh3nuqaws/Sev8YgazrPdNTO3PDxGhf03SIJN5G3N9PakNWPIVvnbIQDtGczxww9bkK79WBk0ougi9R2yKA/CL6s79NbTBohiPLoj6wEtOzloixpqxiW1MV96jFqlXSNuxzBQR0Yan0WX2bwqYEuPzCBK8pR87/rXKx6x2Hc7czO5Itv06I4/+aZM9C0UpNP8I6WgA+FDsK6iBVh+NP5wVg0g2a4z9tM20DXyOc6QeMlE/wB0j0=
  gem: tp_common
  on:
    tags: true
    branch: master
    repo: TINYhr/tp_common
